### PR TITLE
Use Kramdown instead of Maruku to process markdown

### PR DESCRIPTION
**Pull request by benbalter**
The default markdown processor "Maruku" is very particular about strict markdown.
Tell Jekyll to use Kramdown instead to allow the site to build.

PING: @leahbannon 

:fire: :rotating_light: :fire_engine: :rocket: :smile:

### CODE REVIEW

**Comment by leahbannon** [comment]
But the index file is working and it's the same as the other pages?

And several pages that were working just randomly stopped working with no changes made.

**Comment by benbalter** [comment]
_Merging this pull request will allow the site to build as is_. The site has not built for the past 43 commits. Check your email for the build failure notifications. You should have 43 of them.

Specifically, per [the Markdown guide](http://guides.github.com/overviews/mastering-markdown/) you'll want to add spaces after headings and bullets.

### This

``` markdown
# My awesome heading

* One
* Two
* Three
```

### Not This

``` markdown
#Potentially a heading

*is this a list item?
*or is this an unclosed italicized phrase?
```

**Comment by leahbannon** [comment]
Ok thanks for the help. Sorry I still don't understand why it worked some of the time and not others, though. I don't have any build failure emails.

**Comment by benbalter** [comment]
> But the index file is working and it's the same as the other pages?

To clarify, building is binary with Maruku. If one page has an error, the entire site fails to build. With Kramdown, it can be a bit smarter about ambiguous cases, and will continue to build, even if it can't.

You can see the specific pages that caused the build to fail in your email, but likely it's a combination of the lack of space, plus something else that has special meaning on the same line (such as a `?`, `[`, or `(`) that made it impossible for Maruku to understand what you wanted to happen.

**Pull request merged**
